/**
 * Generated by Jay Wu
 */
import React from 'react';

import { 
    Container,
    Row,
    Col,
    Card,
    CardTitle,
    CardBody,
    FormFeedback,
    Badge,
    CustomInput,
    Form, 
    FormGroup, 
    Label, 
    Input, 
    FormText
} from '../../../components';

import { HeaderMain } from "../../components/HeaderMain";
import { HeaderDemo } from "../../components/HeaderDemo";

class ImageInput extends React.Component {

    constructor(props) {
        super(props);

        this.state = {
            image: {
                id: -1,
                image: 'https://p2.bahamut.com.tw/B/2KU/36/1c3353d7b0e89bff5c3e62a9f518p4s5.JPG?v=1590641280338',
                file: null,
                filename: '',
            }
        };

        this.headerCheckboxRef = React.createRef();
    }

    canvasDataURL(path, obj, callback)  {
        var img = new Image();
        img.src = path;
        img.onload = function(){
        var that = this;
        
        // 依照比例壓縮
        var w = that.width,
        h = that.height,
        scale = w / h;
        w = obj.width || w;
        h = obj.height || (w / scale);
        
        // 品質 0.8
        var quality = 0.8;
        // 建立 canvas
        var canvas = document.createElement('canvas');
        var ctx = canvas.getContext('2d');

        var anw = document.createAttribute("width");
        anw.nodeValue = w;
        var anh = document.createAttribute("height");
        anh.nodeValue = h;
        
        canvas.setAttributeNode(anw);
        canvas.setAttributeNode(anh); 
        ctx.drawImage(that, 0, 0, w, h);
        if(obj.quality && obj.quality <= 1 && obj.quality > 0){
            quality = obj.quality;
        }
        // quality值越小，所繪制出的圖像越模糊
        var base64 = canvas.toDataURL('image/jpeg', quality);
        // 回調函數返回base64的值
        callback(base64);
        }
    }

    getBase64(file) {
        return new Promise((resolve, reject) => {
            const reader = new FileReader();
            reader.readAsDataURL(file);
            reader.onload = () => {
                this.canvasDataURL(reader.result, { width: 1080 }, (base64String)=>{
                    resolve(base64String)
                })
            };
            reader.onerror = error => reject(error);
        });
    }

    async onChangePhoto(e) {
        let targetFiles = e.target.files;

        for (var i in targetFiles) {
            if (!(targetFiles[i] instanceof File)) {
                continue;
            }

            let base64String = await this.getBase64(targetFiles[i]);

            let item = {
                id: 1,
                image: base64String,
                file: targetFiles[i],
                filename: '...'
            };

            this.setState({
                image: item
            });
        }
    }

    cancelPhoto() {
        this.setState({
          image: {
              id: -1,
              image: '',
              file: null,
              filename: '',
          }
        })
      }

    render() {
        return (
            <React.Fragment>
                <Container>
                    <HeaderMain 
                        title="Image Input"
                        className="mb-5 mt-4"
                    />

                    <Row> 
                        <Col lg={ 12 }>
                            <HeaderDemo 
                                no={1} 
                                title="Basic Inputs" 
                                subTitle="Indicate the current page’s location within a navigational hierarchy that automatically adds separators via CSS."
                            />

                            {
                                this.state.image.id !== -1
                                ?   <label className="fileinput" style={{ width: "200px" }}>
                                        <input 
                                            type="file" id="file" aria-label="File browser example" style={{ display: "none" }} 
                                            onChange={this.onChangePhoto.bind(this)}
                                            accept="image/*" multiple={true}
                                        />
                                        <div className="thumbnail">
                                            <img src={this.state.image.image} />
                                        </div>
                                    </label>
                                :   <label className="fileinput" style={{ width: "200px" }}>
                                        <input 
                                            type="file" id="file" aria-label="File browser example" style={{ display: "none" }} 
                                            onChange={this.onChangePhoto.bind(this)}
                                            accept="image/*" multiple={true}
                                        />
                                        <div className="thumbnail">
                                            <img src="https://demos.creative-tim.com/paper-dashboard-pro-react/static/media/image_placeholder.ebe9884b.jpg" />
                                        </div>
                                    </label>
                            }
                        </Col>
                    </Row>

                </Container>
            </React.Fragment>
        );
    }
}

export default ImageInput;